<a href="https://colab.research.google.com/github/VicenteMercado/LabsIA/blob/main/ICI3244_1_Laboratorio_1_Grupo_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Integrantes:
- Benjamín Díaz
- Benjamín Fernández
- Vicente Mercado
- Thomas Molina

#Instrucciones:

El laboratorio se dividirá en 2 secciones.
En la primera sección tendrán que definir las funciones necesarias para explorar un problema desde un estado inicial y reconocer si este estado es el estado final.(15 pts)

En la segunda sección se tendrá que implementar un algoritmo de búsqueda informado, el cual nos permita obtener el path desde un estado inicial hasta un estado final.(35 pts)

Finalmente, se asignará un puntaje de entre 0 y 10 puntos por la cantidad/calidad de los comentarios que se agreguen al código explicando cada uno de sus componentes. 

El Laboratorio deberá ser trabajado en grupos de entre 3 (min) y 5(max) estudiantes. La fecha de entrega del Lab 1 es el 24/04. La entrega se realizará a través del aula, antes de las 23.59 del dia 24/04.

#Instalación de librerías necesarias

In [ ]:
# Importar librería numpy
import numpy as np

#**Seccion 1**

#Estado

En el siguiente cuadro se muestra el estado inicial del problema. Cada estado se compone de una matriz de tamaño 16x16. Los elementos de esta matriz pueden variar entre los valores 0 y 1 (Una matriz binaria).

In [ ]:
# Set a random seed for reproducibility
np.random.seed(123)

# Generate a 16x16 matrix of random values between 0 and 1
initial_state = np.random.randint(2, size=(16, 16))


In [ ]:
# function that print a given matrix
def print_matrix(state):
  for row in state:
    print(row)

In [ ]:
print_matrix(initial_state)

[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


#Acción
Para este estado se define que una accion es intercambiar el valor de un elemento de tal forma que:

*   Si el elemento tiene un valor 1 se le asigna un valor 0
*   Si el elemento tiene un valor 0 se le asigna un valor 1

El siguiente codigo muestra como se realoza una acción en el elemento [0,0] del estado inicial.

In [ ]:
#initial_state[0, 0] = 1
#print_matrix(initial_state)

En base a esto se pide completar la funcóon *expand_node(state)*. Donde la funcion retorna una lista de todos los hijos que se pueden generar de un estado state dado. (10 pts)

##**Desarrollo Sección 1 (Acción):**
---
La acción se define como intercambiar el valor de un único elemento de la matriz.

La función de expansión debe, a partir de un estado entregado, ir cambiando el valor de cada uno de sus elementos mientras guarda cada estado generado en una lista, la cual se entregará al final del recorrido de la matriz.

---

**Descripción del Algoritmo:** El algoritmo recorre la matriz intercambiando el valor de la posición actual y de la posición que anteriormente recorrió (en caso de existir), de manera que se asegure que sólo un elemento del estado inicial sea intercambiado. Mientras realiza el recorrido, el algoritmo guarda cada estado generado en una lista. Al finalizar el recorrido de la matriz, se retorna la lista con todos los estados generados.

In [ ]:
#@title Funciones Adicionales

# Función para obtener el largo de una fila
def getNumRow(state):
  len = state.size // state[0].size
  return len

# Función para obtener el largo de una columna
def getNumCol(state):
  len = state[0].size
  return len

# Función que intercambia los valores de una casilla de 0 a 1 y viceversa.
def intercambiar(i, j, state):
  if (state[i][j] == 0):
    state[i][j] = 1
    return state
  state[i][j] = 0
  return state

print(getNumRow(initial_state))
print(getNumCol(initial_state))

16
16


In [ ]:
#@title Función Expand Node: 
# En la función de expansión se recorrerá la matriz completa, mientras se 
# intercambian los valores de las casillas correspondientes.
def expand_node(state):
  
  # Declarar la lista de estados.
  listStates = []

  # Obtener el largo de la matriz.
  rows = getNumRow(state)
  cols = getNumCol(state)

  # Recorrer la Matriz.
  for i in range (rows):
    for j in range (cols):

      # Intercambiar los valores de la casilla actual.
      intercambiar(i, j, state)

      # A continuación se considera si la posición anterior también necesita ser
      # intercambiada, el único caso donde esto no ocurre sería en el primer
      # elemento, ya que no hay casilla anterior.
      if not (i == 0 and j == 0):

        # Ahora se identificará que casilla corresponde a la anterior, aquí
        # pueden existir 2 casos: Que la posición actual y su predecesor estén
        # en la misma fila o que se encuentren en filas diferentes.

        # Caso Misma Fila (Basta con saber si la columna actual no es la primera):
        if j != 0:
          intercambiar(i,j-1,state)
        # Caso Distinta Fila (La columna actual no es la primera):
        else:
          intercambiar(i-1,cols-1,state) # Última posición de la columna anterior.

      # Se guarda el estado en una variable auxiliar.
      aux = state.copy()

      # Se agrega el estado en la lista de estados.
      listStates.append(aux)

  # Retornar la lista de estados generada.
  return listStates


lista=expand_node(initial_state)
print(len(lista))
print(lista[254])
#[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]


256
[[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
 [0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
 [1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
 [0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
 [0 1 1 1 0 1 0 0 1 1 1 0 1 1 1 0]]





# Estado Meta

Para el ejercicio se considera como estado meta (o final) la matriz que se genera al usar la semilla 124 en numpy. La cual se muestra a continuación.



In [ ]:
# Set a random seed for reproducibility
np.random.seed(124)

# Generate a 16x16 matrix of random values between 0 and 1
final_state = np.random.randint(2, size=(16, 16))

print_matrix(final_state)

[0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
[1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1]
[1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1]
[0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0]
[0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1]
[1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0]
[0 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1]
[0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1]
[1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0]
[1 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1]
[1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1]
[1 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1]
[0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1]
[0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0]


Teniendo este estado meta, se requiere que implemente la función *is_goal(state)*. la cual devuelve un valor booleano true si el estado state es el estado meta. En caso de que no sea el estado meta la funcion debera devolvera un valor booleano false. (5 pts)

---
**Descripción del Algoritmo:** Se deben recorrer las 2 matrices (tanto actual como meta), comparando cada uno de sus elementos en orden. Si algún elemento no coincide se retornará *false*, si se logra recorrer toda la matriz sin encontrar diferencias, entonces se retorna *true*.

In [ ]:
#@title Función Is-Goal:
#Función que verifica si el estado actual es el estado objetivo/meta.
def is_goal(state):
  # Obtener la cantidad de filas y columnas.
  rows = getNumRow(state)
  cols = getNumCol(state)

  # Recorrer las distintas posiciones de un estado.
  for i in range (rows):
    for j in range (cols):

      # Comparar los valores encontrados en las casillas de cada matriz.
      # Si resultan distintas, entonces el estado actual no es el objetivo/meta.
      if state[i,j] != final_state[i,j]:
        return False
  
  # Si se recorre toda la matriz si encontrar fallos, entonces se ha encontrado
  # el estado objetivo/meta y se debe retornar verdadero.
  return True

#**Seccion 2**

En esta esta seccion se debera implementar un algoritmo de busqueda. Para esto tendran que que implementar la función *evaluate(state)* la cual evalua el estado y retorna un el coste de este. Como recomendacion considere que cada elemento del estado el cual no sea igual al del estado meta incrementa en 1 el coste de este. (5 pts)



---
**Definición de Costo**: El costo que posee un estado se considerará como la cantidad de casillas que a comparación con las casillas del estado final resultan distintas.

**Descripción del Algoritmo**: El algoritmo busca obtener el *costo* de un estado según la definición anterior. Para ello, recorre y compara toda la matriz del estado actual y registra con un contador la cantidad de casillas distintas que existen en aquel estado. Este número se retornará como el costo al final de la función.

In [ ]:
#@title Función Evaluate:
#Función que evaluará un costo para cada estado.
def evaluate(state):
  # Declarar variable para almacenar el costo del estado.
  cost_state = 0

  # Calcular las dimensiones de la matriz (Generalizando el problema a matrices nxn)
  row = getNumRow(state)
  col = getNumCol(state)

  # Recorrer la matriz comparando cada elemento del estado actual con la 
  # matriz del estado final. Si resultan ser distintos el costo aumenta en 1.
  for i in range(row):
    for j in range(col):
      # Comparación de elementos
      if state[i,j] != final_state[i,j]:
        #Aumentar el costo en 1.
        cost_state+=1

  # Retorno el costo obtenido
  return cost_state

---
Teniendo la función de evaluación ya desarrollada es posible implementar el algoritmo de busqueda informado. Para ello deberan escoger **una** (meta)heuristica* Y describir el algoritmo escogido cómo hemos descrito los algoritmos que hemos visto en clases. (15 pts)

*Algunas opciones de (meta)heuristicas pueden ser local search, genetic algorithm, tabu search, simulates annealing entre otros.



## **Local Search (Metaheurística):**

**Descripción de Local Search**: 

El algoritmo busca conseguir un path desde el estado inicial del problema hasta el estado final. 

Para aquello, explorará (utilizando una función de expansión) la vecindad del estado actual, la cual obtendrá tantos nodos posibles como acciones a realizar existan en un estado (256).

Luego, el algoritmo elegirá el mejor camino posible a seguir, esto se consigue obteniendo el costo de cada nodo (en base a una función de evaluación) y guardando el de menor valor encontrado hasta recorrer toda la vecindad.

Cuando se obtenga el nodo mejor más indicado, este se agrega al path y se verifica si es el estado final, si este no es el caso, se repite el procedimiento desde la etapa de expansión. Si se encuentra el caso objetivo, entonces se retorna el path obtenido.


Después deberan implementar el algoritmo en la función *heuristic(initial_state)*. Esta función recibe como parámetro el estado inicial y debe retornar como salida el conjunto de acciones que permita ir desde el estado inicial hasta el estado final. (10 pts)

In [ ]:
#@title Función Heurística
def heuristic(initial_state):
  
  # Crear un path
  path = []

  # Definir un estado inicial
  state = initial_state.copy()

  while(1):
    # Verificar si el nodo es el estado final
    if is_goal(state) == True:
      return path 
    
    # Si no se encuentra en el estado final, se debe expandir el estado actual
    listStates = expand_node(state)

    # Declarar un costo mínimo inicial
    min_cost = float('inf')

    # Recorrer cada posible estado.
    for node in listStates:
      # Evaluar el estado.
      cost = evaluate(node)
      # Si el costo de la evalución es menor al costo mínimo registrado, colocar
      # a este estado como el nuevo mínimo.
      if cost < min_cost:
        min_cost = cost
        min_state = node
    
    # Al ya tener un estado de costo mínimo, se agrega este al path.
    path.append(min_state)

    # Actualizar el estado actual.
    state = min_state

  #Retornar el path
  return path

Ya implementado el algoritmo se pide mostrar en pantalla los estados recorridos desde el estado inicial hasta el estado final (se recomienda utilizar el camino mas corto que hayan encontrado). (5 pts)

In [ ]:
#@title Mostrar el "Path" obtenido.
path = heuristic(initial_state)

#Contador de Acciones
cont = 0

#Estado Inicial
print("Estado Inicial:\n", initial_state, '\n')

for i in path:

  #Caso Final
  if (cont == len(path)-1):
    print("Estado Final:\n", i, '\n')
  #Cualquier otro Caso
  else:
    print("Estado Acción:\n", i, '\n')
  
  #Aumentar el valor del contador.
  cont += 1

print("Cantidad total de Estados en el Path:", len(path))

Estado Inicial:
 [[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
 [0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
 [1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
 [0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
 [0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1]] 

Estado Acción:
 [[0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
 [0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
 [1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 1